---
- name: install tmux and weechat
  apt:
    name:
      - tmux
      - weechat-curses
      - weechat-plugins
      - weechat-python
    update_cache: true
  become: true

- name: add weechat group
  group:
    name: weechat
  become: true

- name: add weechat user
  user:
    name: weechat
    group: weechat
    create_home: true
  become: true

- name: restrict weechat home only to weechat user and group
  file:
    path: /home/weechat
    state: directory
    owner: weechat
    group: weechat
    mode: "0750"
    recurse: true
  become: true

- name: install weechat systemd unit file
  copy:
    src: etc/systemd/system/weechat.service
    dest: /etc/systemd/system/weechat.service
  notify:
    - systemctl daemon-reload
    - systemctl restart weechat
  become: true

- name: start weechat
  systemd:
    name: weechat
    state: started
  become: true
