---
- name: create vhost directories
  ansible.builtin.file:
    path: "{{ nginx_root }}/{{ vhost.servername }}"
    state: directory
    owner: root
    group: www-data
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.servername }}"

- name: create vhost content directories
  ansible.builtin.file:
    path: "{{ nginx_root }}/{{ vhost.servername }}/html"
    state: directory
    owner: root
    group: www-data
    mode: 0775
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.servername }}"

- name: create vhost logs directories
  ansible.builtin.file:
    path: "{{ nginx_root }}/{{ vhost.servername }}/logs"
    state: directory
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.servername }}"

- name: add vhost configuration file
  ansible.builtin.template:
    src: etc/nginx/sites-available/site-vhost.j2
    dest: "/etc/nginx/sites-available/{{ vhost.servername }}.vhost"
    owner: root
    group: root
    mode: 0640
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.servername }}"
  notify: systemctl restart nginx

- name: add vhost configuration symlink
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ vhost.servername }}.vhost"
    dest: "/etc/nginx/sites-enabled/{{ vhost.servername }}.vhost"
    state: link
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.servername }}"
  notify: systemctl reload nginx

- name: check if telegraf is running
  ansible.builtin.systemd:
    name: "telegraf"
  register: telegraf_service_status

- debug:
    var: telegraf_service_status.status.ActiveState

- name: add logrotate configuration
  ansible.builtin.template:
    src: etc/logrotate.d/nginx.j2
    dest: "/etc/logrotate.d/{{ vhost.servername }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost
    label: "{{ vhost.servername }}"
