---
- name: create vhost directories
  ansible.builtin.file:
    path: "{{ nginx_root }}/{{ item.servername }}"
    state: directory
    owner: root
    group: www-data
  with_items: "{{ nginx_vhosts }}"

- name: create vhost content directories
  ansible.builtin.file:
    path: "{{ nginx_root }}/{{ item.servername }}/html"
    state: directory
    owner: root
    group: www-data
    mode: 0775
  with_items: "{{ nginx_vhosts }}"

- name: create vhost logs directories
  ansible.builtin.file:
    path: "{{ nginx_root }}/{{ item.servername }}/logs"
    state: directory
  with_items: "{{ nginx_vhosts }}"

- name: add vhost configuration file for {{ item.servername }}
  ansible.builtin.template:
    src: etc/nginx/sites-available/site-vhost.j2
    dest: "/etc/nginx/sites-available/{{ item.servername }}.vhost"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ nginx_vhosts }}"
  notify: systemctl restart nginx

- name: add vhost configuration sylink for {{ item.servername }}
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item.servername }}.vhost"
    dest: "/etc/nginx/sites-enabled/{{ item.servername }}.vhost"
    state: link
  with_items: "{{ nginx_vhosts }}"
  notify: systemctl reload nginx

- name: add logrotate configuration for {{ item.servername }}
  ansible.builtin.template:
    src: etc/logrotate.d/nginx.j2
    dest: "/etc/logrotate.d/{{ item.servername }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ nginx_vhosts }}"
