---
- block:

  - name: ensure /etc/apt/keyrings exists
    ansible.builtin.file:
      dest: /etc/apt/keyrings/
      state: directory
      mode: 0755

  - name: add Infuxdb GPG key
    ansible.builtin.get_url:
      url: https://repos.influxdata.com/influxdata-archive_compat.key
      dest: /etc/apt/keyrings/influxdata-archive_compat.key
      # yamllint disable-line rule:line-length
      checksum: sha256:393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c

  - name: add Influxdata's repository
    apt_repository:
      # yamllint disable-line rule:line-length
      repo: "deb [signed-by=/etc/apt/keyrings/influxdata-archive_compat.key] https://repos.influxdata.com/debian stable main"
      filename: influxdata

  - name: install influxdb2
    ansible.builtin.apt:
      name:
        - influxdb2
      update_cache: true
      cache_valid_time: 3600

  - name: ensure influxdb is running
    ansible.builtin.systemd:
      state: started
      name: influxdb

  become: "{{ influxdb_become }}"
  become_user: "{{ influxdb_become_user }}"
