---
- block:

  - name: install influxdb
    ansible.builtin.apt:
      name:
        - influxdb
      update_cache: true
      cache_valid_time: 3600

  - name: install /etc/influxdb/influxdb.conf
    ansible.builtin.template:
      src: etc/influxdb/influxdb.conf.j2
      dest: /etc/influxdb/influxdb.conf
      owner: root
      group: root
      mode: "0644"
    notify: systemctl restart influxdb

  - name: ensure influxdb is running
    ansible.builtin.systemd:
      state: started
      name: influxdb

  become: "{{ influxdb_become }}"
  become_user: "{{ influxdb_become_user }}"
