---
- name: install python3-openssl
  apt:
    name: python3-openssl
    update_cache: true
    cache_valid_time: 3600

- name: ensure {{ generate_certificate_base_path }} esists
  file:
    path: "{{ generate_certificate_base_path }}"
    state: directory
    owner: root
    mode: 0700

- name: generate certificate private key
  openssl_privatekey:
    path: "{{ generate_certificate_key_path }}"
    size: 2048
    type: RSA

- name: generate Certificate Signing Request
  openssl_csr:
    path: "{{ generate_certificate_csr_path }}"
    privatekey_path: "{{ generate_certificate_key_path }}"
    organization_name: "{{ generate_certificate_organization_name }}"
    email_address: "{{ generate_certificate_email_address }}"
    common_name: "{{ generate_certificate_domain }}"

- name: generate a certificate for {{ generate_certificate_domain }}
  openssl_certificate:
    path: "{{ generate_certificate_crt_path }}"
    csr_path: "{{ generate_certificate_csr_path }}"
    ownca_path: "{{ generate_certificate_ca_path }}"
    ownca_privatekey_path: "{{ generate_certificate_ca_privatekey_path }}"
    ownca_privatekey_passphrase: "{{ generate_certificate_ca_privatekey_passphrase }}"
    ownca_not_after: "+365d"
    provider: ownca
