---
- name: install openssl and python3-pexpect
  apt:
    name:
      - openssl
      - python3-pexpect
    update_cache: true
    cache_valid_time: 3600

- name: ensure {{ generate_certificate_base_path }} esists
  file:
    path: "{{ generate_certificate_base_path }}"
    state: directory
    owner: root
    mode: 0700

- name: generate certificate private key
  command:
    cmd: openssl genrsa -out {{ generate_certificate_key_path }} 2048

- name: generate Certificate Signing Request
  command:
    cmd: >
      openssl req -new -sha256 -key {{ generate_certificate_key_path }}
        -out {{ generate_certificate_csr_path }}
        -subj "/CN={{ generate_certificate_domain }}"

- name: generate a certificate for {{ generate_certificate_domain }}
  expect:
    command: >
      openssl x509 -req -days 365 -sha256
        -in {{ generate_certificate_csr_path }}
        -CA {{ generate_certificate_ca_path }}
        -CAkey {{ generate_certificate_ca_privatekey_path }}
        -CAcreateserial
        -out {{ generate_certificate_crt_path }}
    responses:
      Enter pass phrase: "{{ generate_certificate_ca_privatekey_passphrase }}"
