---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: debian:11-slim
    commands:
      - apt update && apt install -y ansible python3-pip podman
      - python3 -m pip install "molecule[lint,podman]"
      - molecule lint
