---
kind: pipeline
type: docker
name: default

steps:
  - name: start-systemd
    image: jrei/systemd-debian:11
    privileged: true
    volumes:
      - name: cgroup
        path: /sys/fs/cgroup
    commands:
      - /lib/systemd/systemd
      - apt update && apt install -y ansible python3-pip
      - python3 -m pip install "molecule[lint]"
      - molecule --debug test

volumes:
  - name: cgroup
    host:
      path: /sys/fs/cgroup
