---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: debian:11
    privileged: true
    commands:
      - apt update && apt install -y ansible docker python3-pip
      - python3 -m pip install "molecule[lint,docker]"
      - echo "[registries.search]\nregistries = ['docker.io']" >> /etc/containers/registries.conf
      - molecule test
