---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: debian:11
    privileged: true
    volumes:
      - name: cgroup
      - path: /sys/fs/cgroup
    commands:
      - apt update && apt install -y dbus ansible podman python3-pip
      - python3 -m pip install "molecule[lint,podman]"
      - echo "[registries.search]\nregistries = ['docker.io']" >> /etc/containers/registries.conf
      - echo "[engine]\nevents_logger = 'file'" >> /etc/containers/containers.conf
      - molecule --debug test

volumes:
  - name: cgroup
    host:
      path: /sys/fs/cgroup
