---
namespace: eriol
name: kit
version: 0.6.6
readme: README.md
authors:
  - Daniele Tricoli <eriol@mornie.org>
description: Ansible collection that I wrote for my own use.
license:
  - BSD-3-Clause
tags:
  - linux
  - server
  - collection
