---
- name: install openssl and python3-pexpect
  apt:
    name:
      - openssl
      - python3-pexpect
    update_cache: true
    cache_valid_time: 3600

- name: ensure {{ generate_ca_base_path }} esists
  file:
    path: "{{ generate_ca_base_path }}"
    state: directory
    owner: root
    mode: 0700

- name: generate the root private key
  expect:
    command: openssl genrsa -aes256 -out {{ generate_ca_root_key_path }} 4096
    responses:
      Enter pass phrase: "{{ generate_ca_passphrase }}"

- name: generate and self sign the root certificate
  expect:
    command: >
      openssl req -x509 -new -nodes -sha256 -days 1825 -extensions v3_ca
      -key {{ generate_ca_root_key_path }}
      -out {{ generate_ca_root_certificate }}
      -subj "/C={{generate_ca_country_name}}/ST={{ generate_ca_state_or_province_name }}/O={{ generate_ca_organization_name }}"
    responses:
      Enter pass phrase: "{{ generate_ca_passphrase }}"
