---

- name: install dovecot
  ansible.builtin.apt:
    name:
      - dovecot-core
      - dovecot-imapd
      - dovecot-managesieved
      - dovecot-sieve
      - dovecot-sqlite
    update_cache: true
    cache_valid_time: 3600

- import_tasks: sqlite.yml

- name: disable auth-system.conf.ext and enable auth-sql.conf.ext
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-auth.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^!include auth-system.conf.ext"
      line: "#!include auth-system.conf.ext"
    - regexp: "^#!include auth-sql.conf.ext"
      line: "!include auth-sql.conf.ext"

- name: install dovecot 10-mail.conf
  ansible.builtin.template:
    src: etc/dovecot/conf.d/10-mail.conf.j2
    dest: /etc/dovecot/conf.d/10-mail.conf
  register: dovecot_10_mail_conf

- name: install dovecot 10-master.conf
  ansible.builtin.template:
    src: etc/dovecot/conf.d/10-master.conf.j2
    dest: /etc/dovecot/conf.d/10-master.conf
  register: dovecot_10_master_conf

- name: configure 10-ssl.conf
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^ssl = yes"
      line: "ssl = required"
    - regexp: "^ssl_cert = "
      line: "ssl_cert = <{{ mailserver_tls_cert_file }}"
    - regexp: "^ssl_key = "
      line: "ssl_key = <{{ mailserver_tls_key_file }}"

- name: configure 15-lda.conf
  ansible.builtin.lineinfile:
    path: /etc/dovecot/conf.d/15-lda.conf
    regexp: "^  #mail_plugins ="
    line: "  mail_plugins = $mail_plugins sieve"

- name: configure 15-mailboxes.conf
  ansible.builtin.copy:
    src: etc/dovecot/conf.d/15-mailboxes.conf
    dest: /etc/dovecot/conf.d/15-mailboxes.conf
    owner: root
    group: root

- name: configure 95-stats.conf
  ansible.builtin.template:
    src: etc/dovecot/conf.d/95-stats.conf.j2
    dest: /etc/dovecot/conf.d/95-stats.conf
    owner: root
    group: root

- name: configure dovecot-sql.conf.ext
  ansible.builtin.template:
    src: etc/dovecot/dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/dovecot-sql.conf.ext
    owner: root
    group: root
    mode: 0600
  register: dovecot_sql_conf_ext

- name: reload dovecot on config
  ansible.builtin.systemd:
    name: dovecot
    state: reloaded
