---

- name: install postfix
  ansible.builtin.apt:
    name:
      - postfix
      - postfix-sqlite
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: configure mailname
  ansible.builtin.copy:
    content: "{{ mailserver_mailname }}"
    dest: /etc/mailname

- name: install postfix master.cf
  ansible.builtin.template:
    src: etc/postfix/master.cf.j2
    dest: /etc/postfix/master.cf
  register: postfix_master_cf

- name: install postfix main.cf
  ansible.builtin.template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
  register: postfix_main_cf

- name: install configuration for virtual tables
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    group: postfix
    mode: 0640
  loop:
    - etc/postfix/sqlite_virtual_alias_maps.cf
    - etc/postfix/sqlite_virtual_domains_maps.cf
    - etc/postfix/sqlite_virtual_mailbox_maps.cf

- name: reload postfix on config change
  ansible.builtin.systemd:
    name: postfix
    state: reloaded
  when: postfix_master_cf.changed or postfix_main_cf.changed
