---

- name: install rspamd
  ansible.builtin.apt:
    name:
      - rspamd
      - redis
    update_cache: true
    cache_valid_time: 3600

- name: copy rspamd configuration files
  ansible.builtin.copy:
    src: etc/rspamd/local.d/{{ item }}
    dest: /etc/rspamd/local.d/{{ item }}
  loop:
    - actions.conf
    - classifier-bayes.conf
    - milter_headers.conf
    - redis.conf

- name: reload rspamd
  ansible.builtin.systemd:
    name: rspamd
    state: reloaded
