---

- name: install rspamd
  apt:
    name:
      - rspamd
      - redis
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: copy rspamd configuration files
  copy:
    src: etc/rspamd/local.d/{{ item }}
    dest: /etc/rspamd/local.d/{{ item }}
  loop:
    - actions.conf
    - classifier-bayes.conf
    - milter_headers.conf
    - redis.conf
  become: true

- name: reload rspamd
  systemd:
    name: rspamd
    state: reloaded
  become: true
