---

- name: install sqlite3
  apt:
    name: sqlite3
    update_cache: true
    cache_valid_time: 3600

- name: import schema
  shell: |
    sqlite3 /etc/dovecot/authdb.sqlite << EOF
      CREATE TABLE IF NOT EXISTS alias (
          address VARCHAR(255) NOT NULL PRIMARY KEY,
          goto TEXT NOT NULL,
          domain VARCHAR(128) NOT NULL,
          created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          modified DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
          active CHAR(1) NOT NULL DEFAULT 'Y'
      );
      CREATE TABLE IF NOT EXISTS domain (
          domain VARCHAR(128) NOT NULL PRIMARY KEY,
          description VARCHAR(255) NOT NULL,
          aliases INT(10) NOT NULL DEFAULT 0,
          mailboxes INT(10) NOT NULL DEFAULT 0,
          maxquota BIGINT(20) NOT NULL DEFAULT 0,
          transport VARCHAR(255) DEFAULT NULL,
          backupmx TINYINT(1) NOT NULL DEFAULT 0,
          created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          modified DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
          active CHAR(1) NOT NULL DEFAULT 'Y'
      );
      CREATE TABLE IF NOT EXISTS mailbox (
          username VARCHAR(255) NOT NULL PRIMARY KEY,
          password VARCHAR(255) NOT NULL,
          domain VARCHAR(128) NOT NULL,
          name VARCHAR(255) NOT NULL,
          quota BIGINT(20) NOT NULL DEFAULT 0,
          created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
          modified DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
          active CHAR(1) NOT NULL DEFAULT 'Y'
      );
    EOF

- name: ensure /etc/dovecot/authdb.sqlite is owned by dovecot and postfix
  file:
    path: "{{ mailserver_auth_database }}"
    owner: dovecot
    group: postfix
    mode: "0640"
