---

- name: ensure vmail user exists
  ansible.builtin.user:
    name: "{{ mailserver_vmail_user }}"
    uid: "{{ mailserver_vmail_uid }}"
    group: "{{ mailserver_vmail_group }}"
    home: "{{ mailserver_vmail_dir }}"
    shell: /usr/sbin/nologin
    system: true

- name: restrict vmail directory to vmail user and group
  ansible.builtin.file:
    path: "{{ mailserver_vmail_dir }}"
    state: directory
    owner: "{{ mailserver_vmail_user }}"
    group: "{{ mailserver_vmail_group }}"
    mode: "0770"
