---
docker_become: true
docker_become_user: root

docker_os: "{{ ansible_facts['distribution'] | lower }}"
docker_arch: amd64
docker_distribution_release: "{{ ansible_facts['distribution_release'] }}"
