---
scenario:
  name: default
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: podman-in-docker
    image: jrei/systemd-debian:11
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroup_manager: cgroupfs
    storage_opt: overlay.mount_program=/usr/bin/fuse-overlayfs
    storage_driver: overlay
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
  flake8
