# Default to bullseye, but just set env variable to, for example,
# "debian/buster64" to run test against buster.
OS_TO_TEST = ENV.fetch("OS_TO_TEST", "debian/bullseye64")

Vagrant.configure("2") do |config|
  config.vm.box = OS_TO_TEST
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision "ansible" do |ansible|
    # ansible.verbose = "vvv"
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "test.yml"
  end
end
