---
- block:

  - name: install radicale
    ansible.builtin.apt:
      name:
        - radicale
        - uwsgi
        - uwsgi-plugin-python3
      state: present
      update_cache: true
      cache_valid_time: 3600

  - name: configure radicale
    ansible.builtin.lineinfile:
      path: /etc/radicale/config
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: present
    with_items:
      - regexp: "^#?type = remote_user"
        line: "type = htpasswd"
      - regexp: "^#?htpasswd_filename = /etc/radicale/users"
        line: "htpasswd_filename = /etc/radicale/users"
      - regexp: "^#?htpasswd_encryption = md5"
        line: "htpasswd_encryption = bcrypt"

  - name: set radicale users and password
    ansible.builtin.template:
      src: etc/radicale/users.j2
      dest: /etc/radicale/users
      mode: 0640

  - name: enable radicale uWSGI service
    ansible.builtin.file:
      src: /etc/uwsgi/apps-available/radicale.ini
      path: /etc/uwsgi/apps-enabled/radicale.ini
      state: link
    notify: systemctl restart uwsgi

  become: "{{ radicale_become }}"
  become_user: "{{ radicale_become_user }}"
