---
- block:

  - name: install prerequisites
    ansible.builtin.apt:
      name:
        - default-jre
        - unzip
      update_cache: true
      cache_valid_time: 3600

  - name: ensure marytts group exits
    ansible.builtin.group:
      name: marytts
      system: true

  - name: ensure marytts user exists and has restrictive settings
    ansible.builtin.user:
      name: marytts
      groups: marytts
      password: "*"
      create_home: false
      system: true
      shell: /usr/sbin/nologin

  - name: download marytts in /tmp
    ansible.builtin.get_url:
      url: "{{ marytts_download_url }}"
      dest: /tmp
      checksum: "sha256:{{ marytts_tarball_sha256 }}"

  - name: ensure that the directory where we deploy MaryTTS exists
    ansible.builtin.file:
      path: "{{ marytts_dir }}"
      state: directory

  - name: unarchive marytts tarball into {{ marytts_dir }}
    ansible.builtin.unarchive:
      src: "/tmp/{{ marytts_tarball }}"
      dest: "{{ marytts_dir }}"
      remote_src: true
      owner: marytts
      group: marytts

  - name: install marytts systemd unit file
    ansible.builtin.template:
      src: etc/systemd/system/marytts.service.j2
      dest: /etc/systemd/system/marytts.service
    notify:
      - systemctl daemon-reload

  - name: systemctl enable marytts
    ansible.builtin.systemd:
      name: marytts
      enabled: true

  - name: systemctl start marytts
    ansible.builtin.systemd:
      name: marytts
      state: started

  become: "{{ marytts_become }}"
  become_user: "{{ marytts_become_user }}"
