---
- name: install iptables
  apt:
    name: iptables
    state: present
    update_cache: true
  become: true

- name: use legacy version of iptables
  alternatives:
    name: "{{ item }}"
    path: "/usr/sbin/{{ item }}-legacy"
  with_items:
    - iptables
    - ip6tables
  become: true

# TODO: find a better way, because if enabled the following task make this
# not idempotent.
#
# - name: flush all the iptables rules
#   iptables:
#     flush: true
#   become: true

- import_tasks: rules-generic.yml

- import_tasks: rules-ssh.yml

- import_tasks: rules-dns.yml

- import_tasks: rules-http.yml

- name: set the policy for main chains to DROP
  iptables:
    chain: "{{ item }}"
    policy: DROP
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  become: true

- name: install iptables-persistent and netfilter-persistent
  apt:
    name: ['iptables-persistent', 'netfilter-persistent']
    state: present
  become: true
