---
- name: firewall rule - allow new outgoing DNS
  iptables:
    chain: OUTPUT
    protocol: udp
    destination_port: "53"
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  become: true

- name: firewall rule - allow established incoming DNS
  iptables:
    chain: INPUT
    protocol: udp
    source_port: "53"
    ctstate: ESTABLISHED
    jump: ACCEPT
  become: true
