---
- name: get content of /etc/knockd.conf
  shell:
    cmd: cat /etc/knockd.conf
  register: knockd_conf
  become: true

- name: firewall rule - allow incoming SSH
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "22"
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
  become: true
  when: knockd_conf.stdout.find("dport 22") == -1

- name: firewall rule - allow outgoing SSH
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: "22"
    ctstate: ESTABLISHED
    jump: ACCEPT
  become: true
