---
- name: firewall rule - allow incoming loopback traffic
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: True

- name: firewall rule - allow outgoing loopback traffic
  iptables:
    chain: OUTPUT
    out_interface: lo
    jump: ACCEPT
  become: True

- name: firewall rule - allow established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: True
