---

- name: ensure beehive group exits
  group:
    name: beehive
    system: true

- name: ensure beehive user exists and has restrictive settings
  user:
    name: beehive
    groups: beehive
    password: "*"
    create_home: false
    system: true
    shell: /usr/sbin/nologin

- name: ensure that the directory where we deploy beehive exists
  file:
    path: "{{ beehive_dir }}"
    state: directory
    owner: beehive
    group: beehive
    mode: "0750"

# TODO: download only if not installed or a new version.

- name: download locally beehive in /tmp
  get_url:
    url: "{{ beehive_download_url }}"
    dest: /tmp
    checksum: "sha256:{{ beehive_tarball_sha256 }}"
  delegate_to: localhost
  become: false

- name: unarchive locally beehive
  unarchive:
    src: "/tmp/{{ beehive_tarball }}"
    dest: /tmp
    remote_src: true
  delegate_to: localhost
  become: false

- name: copy beehive binary
  copy:
    src: /tmp/beehive
    dest: "{{ beehive_dir }}"
    owner: beehive
    group: beehive
    mode: "0750"

- name: set cap_net_bind_service=+ep on beehive binary
  capabilities:
    path: "{{ beehive_dir }}/beehive"
    capability: cap_net_bind_service=+ep

- name: install beehive systemd unit file
  template:
    src: etc/systemd/system/beehive.service.j2
    dest: /etc/systemd/system/beehive.service
  notify:
    - systemctl daemon-reload

- name: systemctl enable beehive
  systemd:
    name: beehive
    enabled: true

- name: ensure beehive is running
  systemd:
    name: beehive
    state: started
