---
# The pi user is hardcoded here on purpose.

- name: change password for default pi user
  user:
    name: pi
    update_password: always
    password: "{{ pwd | password_hash('sha512') }}"

- name: set authorized key for user pi copying it from current user
  authorized_key:
    user: pi
    state: present
    key: "{{ lookup('file', key_file) }}"
