---
- name: change password for default user
  user:
    name: rpi_users_user
    update_password: always
    password: "{{ rpi_users_pwd | password_hash('sha512') }}"

- name: set authorized key for default user
  authorized_key:
    user: rpi_users_user
    key: "{{ lookup('file', rpi_users_key_file) }}"
    state: present
