---
- name: install openssh-server
  apt:
    name: openssh-server
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: ensure openssh-server is running
  systemd:
    state: started
    name: sshd

- name: harden openssh-server
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^#?AllowAgentForwarding"
      line: "AllowAgentForwarding no"
    - regexp: "^#?AllowTcpForwarding"
      line: "AllowTcpForwarding no"
    - regexp: "^#?MaxAuthTries"
      line: "MaxAuthTries 3"
    - regexp: "^#?MaxSessions"
      line: "MaxSessions 2"
    - regexp: "^#?PasswordAuthentication"
      line: "PasswordAuthentication no"
    - regexp: "^#?PermitRootLogin"
      line: "PermitRootLogin no"
    - regexp: "^#?PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
    - regexp: "^#?TCPKeepAlive"
      line: "TCPKeepAlive no"
    - regexp: "^#?UseDNS"
      line: "UseDNS no"
    - regexp: "^#?X11Forwarding"
      line: "X11Forwarding no"
  become: true
