---
- name: Setup tailscale.
  become: "{{ tailscale_become }}"
  become_user: "{{ tailscale_become_user }}"
  block:

  - name: Install tailscale dependencies
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
      update_cache: true
      cache_valid_time: 3600

  - name: Add Tailscale's GPG key
    ansible.builtin.get_url:
      # yamllint disable-line rule:line-length
      url: "https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.noarmor.gpg"
      dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
      mode: "0644"

  - name: Add Tailscale's repository
    ansible.builtin.get_url:
      # yamllint disable-line rule:line-length
      url: "https://pkgs.tailscale.com/stable/debian/{{ ansible_distribution_release }}.tailscale-keyring.list"
      dest: /etc/apt/sources.list.d/tailscale.list
      mode: "0644"

  - name: Install tailscale
    ansible.builtin.apt:
      name:
        - tailscale
      update_cache: true
      cache_valid_time: 3600
