---
- name: Converge
  hosts: all
  vars:
    hostname_update_etc_hosts: false
  tasks:
    - name: Test sshd role
      include_role:
        name: sshd
    - name: Test hostname role
      include_role:
        name: hostname
