---
scenario:
  name: default
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: debian11
    image: geerlingguy/docker-debian11-ansible:latest
    pre_build_image: true
    command: /sbin/init
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    cgroup_manager: cgroupfs
    storage_opt: overlay.mount_program=/usr/bin/fuse-overlayfs
    storage_driver: overlay
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
# lint: |
#   set -e
#   yamllint .
#   ansible-lint
