---
scenario:
  name: default
dependency:
  name: galaxy
  enabled: false
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
  flake8
