---
scenario:
  name: default
dependency:
  name: galaxy
  enabled: false
driver:
  name: podman
platforms:
  - name: debian11
    image: jrei/systemd-debian:11
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint
  flake8
