---
- block:

  - name: install ssl-cert
    ansible.builtin.apt:
      name: ssl-cert
      state: present
      update_cache: true
      cache_valid_time: 3600

  - name: ensure {{ snake_oil_cert_root }} esists for each domain
    ansible.builtin.file:
      path: "{{ snake_oil_cert_root }}/{{ item }}"
      state: directory
      owner: root
      group: ssl-cert
      mode: 0750
      recurse: true
    loop: "{{ snake_oil_cert_domains }}"

  # It's fine to use rsa:2048 since this role is used only for testing.
  - name: create certificates for each domain
    ansible.builtin.shell: |
      openssl req -x509 -nodes -newkey rsa:2048 \
        -days {{ snake_oil_cert_days }} -sha256 \
        -keyout {{ snake_oil_cert_root }}/{{ item }}/privkey.pem \
        -out {{ snake_oil_cert_root }}/{{ item }}/fullchain.pem \
        -subj "/CN={{ item }}"
      cp {{ snake_oil_cert_root }}/{{ item }}/fullchain.pem \
         {{ snake_oil_cert_root }}/{{ item }}/chain.pem
    loop: "{{ snake_oil_cert_domains }}"

  - name: find all *.pem files
    ansible.builtin.find:
      path: "{{ snake_oil_cert_root }}"
      file_type: file
      recurse: true
    register: find_result

  - name: fix certificates permissions
    ansible.builtin.file:
      path: "{{ item.path }}"
      owner: root
      group: ssl-cert
      mode: 0640
    with_items: "{{ find_result.files }}"

  become: "{{ snake_oil_cert_become }}"
  become_user: "{{ snake_oil_cert_become_user }}"
