---
- block:

  - name: install nftables
    ansible.builtin.apt:
      name: nftables
      state: present
      update_cache: true
      cache_valid_time: 3600

  - name: install nftables.conf
    ansible.builtin.template:
      src: etc/nftables.conf.j2
      dest: /etc/nftables.conf
      owner: root
      group: root
      mode: 0644
    notify: systemctl restart nftables

  # - name: ensure nftables is enabled
  #   systemd:
  #     name: nftables.service
  #     enabled: true
  #     state: started

  become: "{{ nftables_become }}"
  become_user: "{{ nftables_become_user }}"
