---
- block:
    - name: install nftables
      apt:
        name: nftables
        state: present
        update_cache: true
        cache_valid_time: 3600

    - name: install nftables.conf
      template:
        src: etc/nftables.conf.j2
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: 0644
      notify: systemctl restart nftables
  become: "{{ nftables_become }}"
