---
- block:

  - name: install mosquitto
    ansible.builtin.apt:
      name:
        - mosquitto
        - mosquitto-clients
        - python3-pexpect
      update_cache: true
      cache_valid_time: 3600

  - name: create /etc/mosquitto/passwd with user "{{ mosquitto_user }}"
    ansible.builtin.expect:
      command: mosquitto_passwd -c /etc/mosquitto/passwd {{ mosquitto_user }}
      responses:
        (?i)password: "{{ mosquitto_password }}"

  - name: ensure /etc/mosquitto/passwd has restrictive persmissions
    ansible.builtin.file:
      path: /etc/mosquitto/passwd
      owner: mosquitto
      group: root
      mode: 0640

  - name: get available groups
    ansible.builtin.getent:
      database: group

  - name: add mosquitto user to ssl-cert group
    ansible.builtin.user:
      name: mosquitto
      groups: ssl-cert
      append: true
    become: true
    when:
      - mosquitto_add_to_ssl_cert_group and "ssl-cert" in ansible_facts.getent_group

  - name: set mosquitto config file
    ansible.builtin.template:
      src: etc/mosquitto/conf.d/default.conf.j2
      dest: /etc/mosquitto/conf.d/default.conf
      owner: root
      group: root
      mode: 0640
    notify: systemctl restart mosquitto

  - name: ensure mosquitto is running
    ansible.builtin.systemd:
      state: started
      name: mosquitto

  become: "{{ mosquitto_become }}"
  become_user: "{{ mosquitto_become_user }}"
