---
- name: systemctl daemon-reload
  systemd:
    daemon_reload: true
  become: "{{ adguardhome_become }}"
  become_user: "{{ adguardhome_become_user }}"

- name: systemctl restart adguardhome
  systemd:
    name: adguardhome.service
    state: restarted
  become: "{{ adguardhome_become }}"
  become_user: "{{ adguardhome_become_user }}"
