---
- block:
    - name: perform apt update
      ansible.builtin.apt:
        cache_valid_time: 3600
        force_apt_get: true
        update_cache: true

    - name: check upgradable packages
      ansible.builtin.command: apt list --upgradable
      register: apt_result

    - name: show apt list --upgradable output
      ansible.builtin.debug:
        var: apt_result.stdout_lines

    - name: upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

  become: "{{ apt_dist_upgrade_become }}"
  become_user: "{{ apt_dist_upgrade_become_user }}"
