---
- name: perform apt update
  apt:
    cache_valid_time: 3600
    force_apt_get: true
    update_cache: true

- name: check upgradable packages
  command: apt list --upgradable
  register: apt_result

- name: show apt list --upgradable output
  debug:
    var: apt_result.stdout_lines

- name: update all packages
  apt:
    upgrade: dist
