---
adguardhome_become: true
adguardhome_become_user: root

adguardhome_version: v0.107.7
adguardhome_tarball_armv7l: AdGuardHome_linux_armv7.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_armv7l_sha256: bb3b977e59674c1aa41b2826f7c8b79116d39913af87a4be983fcbdd583fba0b
adguardhome_tarball_x86_64: AdGuardHome_linux_amd64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_x86_64_sha256: 71b4e5541946745804cf66faa5bd1227bc947f8c055e76702c2926bd7ef91735
adguardhome_tarball_aarch64: AdGuardHome_linux_arm64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_aarch64_sha256: 4ca6776ce339a2adf41ad2e7f627cdc98ebed8b8b89dfd7eaf62f41311bfd747

# yamllint disable-line rule:line-length
adguardhome_tarball: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower, default=adguardhome_tarball_x86_64) }}"
# yamllint disable-line rule:line-length
adguardhome_tarball_sha256: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower+'_sha256', default=adguardhome_tarball_x86_64_sha256) }}"

# yamllint disable-line rule:line-length
adguardhome_download_url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguardhome_version }}/{{ adguardhome_tarball }}"

adguardhome_dir: /srv/AdGuardHome

adguardhome_user: admin
adguardhome_password: changeme

adguardhome_bind_host: 0.0.0.0

adguardhome_upstream_dns:
  - https://dns10.quad9.net/dns-query

adguardhome_add_to_ssl_cert_group: false
