---
adguardhome_become: true
adguardhome_become_user: root

adguardhome_version: v0.107.72
adguardhome_tarball_armv7l: AdGuardHome_linux_armv7.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_armv7l_sha256: 13704b5088f5c492e8a6e161636c8d3e2722c2eebc0c4306ffca1be9bfa25d55
adguardhome_tarball_x86_64: AdGuardHome_linux_amd64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_x86_64_sha256: cf25794597a2f5b6cd8cd3670439db6f548c59af4ace392e40055b90e80c9329
adguardhome_tarball_aarch64: AdGuardHome_linux_arm64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_aarch64_sha256: 5332366407f825b5929b492db953aab9ede99f9e75d6ecee1b9ea296d95a523e

# yamllint disable-line rule:line-length
adguardhome_tarball: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower, default=adguardhome_tarball_x86_64) }}"
# yamllint disable-line rule:line-length
adguardhome_tarball_sha256: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower+'_sha256', default=adguardhome_tarball_x86_64_sha256) }}"

# yamllint disable-line rule:line-length
adguardhome_download_url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguardhome_version }}/{{ adguardhome_tarball }}"

adguardhome_dir: /srv/AdGuardHome

adguardhome_user: admin
adguardhome_password: changeme

adguardhome_bind_host: 0.0.0.0
adguardhome_bind_port: 80

adguardhome_upstream_dns:
  - https://dns10.quad9.net/dns-query

adguardhome_add_to_ssl_cert_group: false
