---
adguardhome_become: true
adguardhome_become_user: root

adguardhome_version: v0.103.3
adguardhome_tarball_armv7l: AdGuardHome_linux_armv7.tar.gz
adguardhome_tarball_armv7l_sha256: 8dcfeca7a345ff3451f8ba20100aaef8bb9f8d05dfb2d9b619c019000fa00edc
adguardhome_tarball_x86_64: AdGuardHome_linux_amd64.tar.gz
adguardhome_tarball_x86_64_sha256: 077fb5262129535f3fdc47379fdd573a68aade62cdbdac02919b69de777df3ea

adguardhome_tarball: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower, default=adguardhome_tarball_x86_64) }}"
adguardhome_tarball_sha256: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower+'_sha256', default=adguardhome_tarball_x86_64_sha256) }}"

adguardhome_download_url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguardhome_version }}/{{ adguardhome_tarball }}"

adguardhome_dir: /srv/AdGuardHome

adguardhome_user: admin
adguardhome_password: changeme

adguardhome_bind_host: 0.0.0.0

adguardhome_add_to_ssl_cert_group: false
