---
adguardhome_become: true
adguardhome_become_user: root

adguardhome_version: v0.107.74
adguardhome_tarball_armv7l: AdGuardHome_linux_armv7.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_armv7l_sha256: 446a94e6ccac7c09cf7082494f033d18afe67be38b1d33b6971c6362ab9cb1f4
adguardhome_tarball_x86_64: AdGuardHome_linux_amd64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_x86_64_sha256: d569389db0ac9b9bbd9a5a0c5594e532bc30b1c28cfa5b067335f9482d7e181c
adguardhome_tarball_aarch64: AdGuardHome_linux_arm64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_aarch64_sha256: 57dfb53c3bc9007207596de1221b9540e6e4cff7ba043f839e5499621f3f1d77

# yamllint disable-line rule:line-length
adguardhome_tarball: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_facts['architecture']|lower, default=adguardhome_tarball_x86_64) }}"
# yamllint disable-line rule:line-length
adguardhome_tarball_sha256: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_facts['architecture']|lower+'_sha256', default=adguardhome_tarball_x86_64_sha256) }}"

# yamllint disable-line rule:line-length
adguardhome_download_url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguardhome_version }}/{{ adguardhome_tarball }}"

adguardhome_dir: /srv/AdGuardHome

adguardhome_user: admin
adguardhome_password: changeme

adguardhome_bind_host: 0.0.0.0
adguardhome_bind_port: 80

adguardhome_upstream_dns:
  - https://dns10.quad9.net/dns-query

adguardhome_add_to_ssl_cert_group: false
