---
adguardhome_become: true
adguardhome_become_user: root

adguardhome_version: v0.107.69
adguardhome_tarball_armv7l: AdGuardHome_linux_armv7.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_armv7l_sha256: 38c1914641eb954d4f9af99128d3e425b2d29eac163183fee5f63a74029d916f
adguardhome_tarball_x86_64: AdGuardHome_linux_amd64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_x86_64_sha256: 36d82638a30d436d18db3e6f8aaeabe8d5f684e0d451127b8d18d5553a3e5325
adguardhome_tarball_aarch64: AdGuardHome_linux_arm64.tar.gz
# yamllint disable-line rule:line-length
adguardhome_tarball_aarch64_sha256: 34298af99fda196ddbc617da01bc9d8b5ca3fc7636717d786c5a96f6b4dfa0ae

# yamllint disable-line rule:line-length
adguardhome_tarball: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower, default=adguardhome_tarball_x86_64) }}"
# yamllint disable-line rule:line-length
adguardhome_tarball_sha256: "{{ lookup('vars', 'adguardhome_tarball_'+ansible_architecture|lower+'_sha256', default=adguardhome_tarball_x86_64_sha256) }}"

# yamllint disable-line rule:line-length
adguardhome_download_url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguardhome_version }}/{{ adguardhome_tarball }}"

adguardhome_dir: /srv/AdGuardHome

adguardhome_user: admin
adguardhome_password: changeme

adguardhome_bind_host: 0.0.0.0
adguardhome_bind_port: 80

adguardhome_upstream_dns:
  - https://dns10.quad9.net/dns-query

adguardhome_add_to_ssl_cert_group: false
