---
- block:

  - name: ensure /etc/apt/keyrings exists
    ansible.builtin.file:
      dest: /etc/apt/keyrings/
      state: directory
      mode: 0755

  - name: add Influxdb GPG key
    ansible.builtin.get_url:
      url: https://repos.influxdata.com/influxdata-archive_compat.key
      dest: /etc/apt/keyrings/influxdata-archive_compat.key
      # yamllint disable-line rule:line-length
      checksum: sha256:393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c

  - name: add Influxdata's repository
    apt_repository:
      # yamllint disable-line rule:line-length
      repo: "deb [signed-by=/etc/apt/keyrings/influxdata-archive_compat.key] https://repos.influxdata.com/debian stable main"
      filename: influxdata

  - name: install telegraf
    ansible.builtin.apt:
      name:
        - telegraf
      update_cache: true
      cache_valid_time: 3600

  - name: install telegraf.conf
    template:
      src: etc/telegraf/telegraf.conf.j2
      dest: /etc/telegraf/telegraf.conf
    notify:
      - systemctl restart telegraf

  - name: install configurations
    ansible.builtin.copy:
      dest: "/etc/telegraf/telegraf.d/{{ item.name }}"
      content: "{{ item.content }}"
    loop: "{{ telegraf_configs|flatten(levels=1) }}"
    notify:
      - systemctl restart telegraf

  become: "{{ telegraf_become }}"
  become_user: "{{ telegraf_become_user }}"
