---
- name: install ssl-cert
  apt:
    name: ssl-cert
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: ensure /var/lib/dehydrated/certs esists for each domain
  file:
    path: "/var/lib/dehydrated/certs/{{ item.cname }}"
    state: directory
    owner: root
    group: ssl-cert
    mode: 0750
    recurse: true
  loop: "{{ domains }}"

# It's fine to use rsa:2048 since this role is used only for testing.
- name: create certificates for each domain
  shell: |
    openssl req -x509 -nodes -newkey rsa:2048 -days 365 -sha256 \
      -keyout /var/lib/dehydrated/certs/{{ item.cname }}/privkey.pem \
      -out /var/lib/dehydrated/certs/{{ item.cname }}/fullchain.pem \
      -subj "/CN={{ item.cname }}"
    cp /var/lib/dehydrated/certs/{{ item.cname }}/fullchain.pem \
       /var/lib/dehydrated/certs/{{ item.cname }}/chain.pem
  loop: "{{ domains }}"

- name: find all *.pem files
  find:
    path: /var/lib/dehydrated/certs/
    file_type: file
    recurse: true
  register: find_result

- name: fix certificates permissions
  file:
    path: "{{ item.path }}"
    owner: root
    group: ssl-cert
    mode: 0640
  with_items: "{{ find_result.files }}"
